"""Add user_id column to students table

Revision ID: 60d0e234d275
Revises: f353ff9b5b94
Create Date: 2025-04-13 10:03:50.694269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d0e234d275'
down_revision = 'f353ff9b5b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('enrollment_date', sa.Date(), nullable=True))
        batch_op.alter_column('id_card',
               existing_type=sa.VARCHAR(length=18),
               nullable=True)
        batch_op.create_foreign_key('fk_students_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('passed_exam')
        batch_op.drop_column('social_practice')
        batch_op.drop_column('has_application')
        batch_op.drop_column('ethnicity')
        batch_op.drop_column('has_failed_course')
        batch_op.drop_column('college')
        batch_op.drop_column('league_member_id')
        batch_op.drop_column('class_approved')
        batch_op.drop_column('league_branch')
        batch_op.drop_column('political_status')
        batch_op.drop_column('league_join_date')
        batch_op.drop_column('english_level')
        batch_op.drop_column('volunteer_hours')
        batch_op.drop_column('hometown')
        batch_op.drop_column('application_date')
        batch_op.drop_column('scholarship')
        batch_op.drop_column('awards')
        batch_op.drop_column('comprehensive_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprehensive_score', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('awards', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('scholarship', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('application_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('hometown', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('volunteer_hours', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('english_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('league_join_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('political_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('league_branch', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('class_approved', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('league_member_id', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('college', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_failed_course', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ethnicity', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('has_application', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('social_practice', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('passed_exam', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint('fk_students_user_id_users', type_='foreignkey')
        batch_op.alter_column('id_card',
               existing_type=sa.VARCHAR(length=18),
               nullable=False)
        batch_op.drop_column('enrollment_date')
        batch_op.drop_column('department')
        batch_op.drop_column('address')
        batch_op.drop_column('email')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
