"""Add additional fields to Student model

Revision ID: 6f70965a812c
Revises: 60d0e234d275
Create Date: 2025-04-13 10:10:02.011617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f70965a812c'
down_revision = '60d0e234d275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ethnicity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hometown', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('political_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('league_member_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('league_branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('league_join_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('has_application', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('application_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('passed_exam', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('class_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_failed_course', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('comprehensive_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('english_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('scholarship', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('volunteer_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('awards', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('social_practice', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('social_practice')
        batch_op.drop_column('awards')
        batch_op.drop_column('volunteer_hours')
        batch_op.drop_column('scholarship')
        batch_op.drop_column('english_level')
        batch_op.drop_column('comprehensive_score')
        batch_op.drop_column('has_failed_course')
        batch_op.drop_column('class_approved')
        batch_op.drop_column('passed_exam')
        batch_op.drop_column('application_date')
        batch_op.drop_column('has_application')
        batch_op.drop_column('league_join_date')
        batch_op.drop_column('league_branch')
        batch_op.drop_column('league_member_id')
        batch_op.drop_column('political_status')
        batch_op.drop_column('hometown')
        batch_op.drop_column('ethnicity')

    # ### end Alembic commands ###
