"""Update StudentFile model with file size and type fields

Revision ID: 9e30a009985b
Revises: 6f70965a812c
Create Date: 2025-04-13 10:48:15.162374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e30a009985b'
down_revision = '6f70965a812c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_files', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###
