"""Add score_configs table

Revision ID: a4de38a992c5
Revises: 9e30a009985b
Create Date: 2025-04-13 18:30:57.426584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4de38a992c5'
down_revision = '9e30a009985b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.Column('score_config_id', sa.Integer(), nullable=True),
    sa.Column('base_score', sa.Float(), nullable=True),
    sa.Column('academic_score', sa.Float(), nullable=True),
    sa.Column('scholarship_score', sa.Float(), nullable=True),
    sa.Column('volunteer_score', sa.Float(), nullable=True),
    sa.Column('english_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('passed_base_conditions', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('score_detail_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['score_config_id'], ['score_configs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_scores')
    op.drop_table('score_configs')
    # ### end Alembic commands ###
